# Generated by Django 6.0.7 on 2026-07-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_account',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
